paths:
  - Configuration
  - ./ext_typoscript_setup.typoscript

filePatterns:
  - '*.typoscript'
  - '*.tsconfig'

excludePatterns:
  - 'Main.tsconfig'

sniffs:
  - class: Indentation
    parameters:
      useSpaces: true
      indentPerLevel: 2
      indentConditions: false
  - class: DeadCode
  - class: OperatorWhitespace
  - class: RepeatingRValue
    disabled: true
  - class: DuplicateAssignment
  - class: EmptySection
  - class: NestingConsistency
    parameters:
      commonPathPrefixThreshold: 1
