# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Typoheads\Formhandler\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  cache.formhandler_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['formhandler_cache']

  Typoheads\Formhandler\Session\Typo3Session:
    arguments:
      $cache: '@cache.formhandler_cache'
